
export { default as Header } from "./Header/Header"
export { MainHeader as MainHeader } from "./Header/Header"
export { default as Hero } from "./Hero/Hero"
export { default as Collection } from "./Collection/Collection"
export { default as TopItems } from "./TopItems/TopItems"
export { default as About } from "./About/About"
export { default as Achievement } from "./Achievement/Achievement"
export { default as GoodSeller } from "./GoodSeller/GoodSeller"
export { default as Insights } from "./Insights/Insights"
export { default as NewsLetters } from "./NewsLetters/NewsLetters"
export { default as Footer } from "./Footer/Footer"